# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box =  "bento/ubuntu-16.04"

  config.vm.network "private_network", ip: "192.168.33.22"
  config.vm.hostname = "webadv"

   config.vm.provider "virtualbox" do |vb|	
	vb.memory = "2048"
	vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
  config.vm.provision :shell, path: "bootstrap.sh"

end


